development: &default
  adapter: "mysql2"
  user: "" 
  password: "" 
  database: "bbs_development"
  host: "localhost" 
  port: 3306
  encoding: "utf8" 
  socket: 

test:
  <<: *default
  database: "bbs_test" 

production:
  <<: *default
  database: "bbs_production"